import * as k8s from '@kubernetes/client-node';
import stream from 'stream';

import {
  getCoreV1Api,
  getCustomObjectsApi,
  getNamespace,
  getKubeConfig,
} from './client.js';
import { CHE_GATEWAY_CONTAINER, EXEC_TIMEOUT_MS } from '../types.js';
import type { ExecResult } from '../types.js';

export async function findPodForWorkspace(
  workspaceName: string,
): Promise<{ podName: string; containers: string[] }> {
  const coreApi = getCoreV1Api();
  const ns = getNamespace();

  const podList = await coreApi.listNamespacedPod({
    namespace: ns,
    labelSelector: `controller.devfile.io/devworkspace_name=${workspaceName}`,
  });

  const runningPod = podList.items.find(
    (pod: any) => pod.status?.phase === 'Running',
  );

  if (!runningPod) {
    const phase = await getWorkspacePhase(workspaceName);
    throw new WorkspaceNotReadyError(workspaceName, phase);
  }

  const containers = (runningPod.spec?.containers ?? []).map(
    (c: any) => c.name,
  );

  return {
    podName: runningPod.metadata!.name!,
    containers,
  };
}

export class WorkspaceNotReadyError extends Error {
  public readonly phase: string;
  public readonly retryable: boolean;

  constructor(workspaceName: string, phase: string) {
    const retryable = phase === 'Starting';
    const sessionHint =
      phase === 'Starting'
        ? ' Any previous agent sessions have been lost — start a new agent session once the workspace is Running.'
        : '';
    const retryHint = retryable ? ' Retry in a few seconds.' : '';

    let message: string;
    switch (phase) {
      case 'Starting':
        message = `Workspace "${workspaceName}" is starting (no running pod yet).${sessionHint}${retryHint}`;
        break;
      case 'Stopping':
      case 'Stopped':
        message = `Workspace "${workspaceName}" is ${phase.toLowerCase()}.`;
        break;
      case 'Failed':
        message = `Workspace "${workspaceName}" has failed.`;
        break;
      case 'unknown':
        message = `Workspace "${workspaceName}" not found.`;
        break;
      default:
        message = `Workspace "${workspaceName}" is in phase "${phase}" but has no running pod.${sessionHint}${retryHint}`;
        break;
    }

    super(message);
    this.name = 'WorkspaceNotReadyError';
    this.phase = phase;
    this.retryable = retryable;
  }
}

async function getWorkspacePhase(workspaceName: string): Promise<string> {
  try {
    const api = getCustomObjectsApi();
    const ns = getNamespace();
    const dw = (await api.getNamespacedCustomObject({
      group: 'workspace.devfile.io',
      version: 'v1alpha2',
      namespace: ns,
      plural: 'devworkspaces',
      name: workspaceName,
    })) as any;
    return dw.status?.phase || 'Unknown';
  } catch {
    return 'unknown';
  }
}

export function selectContainer(
  containers: string[],
  explicit?: string,
): string {
  if (explicit !== undefined) {
    if (!containers.includes(explicit)) {
      throw new Error(
        `Container "${explicit}" not found. Available: ${containers.join(', ')}`,
      );
    }
    return explicit;
  }

  const devContainer = containers.find(
    (name) => name !== CHE_GATEWAY_CONTAINER,
  );

  if (!devContainer) {
    throw new Error('No dev container found in pod');
  }

  return devContainer;
}

// Generated by Claude Code
export async function execInPod(
  podName: string,
  containerName: string,
  command: string[],
): Promise<ExecResult> {
  const kc = getKubeConfig();
  const ns = getNamespace();
  const kubeExec = new k8s.Exec(kc);

  let stdout = '';
  let stderr = '';

  const stdoutStream = new stream.PassThrough();
  const stderrStream = new stream.PassThrough();

  stdoutStream.on('data', (chunk: Buffer) => {
    stdout += chunk.toString();
  });
  stderrStream.on('data', (chunk: Buffer) => {
    stderr += chunk.toString();
  });

  return new Promise<ExecResult>((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error(`Exec timed out after ${EXEC_TIMEOUT_MS}ms`));
    }, EXEC_TIMEOUT_MS);

    const shellEscape = (arg: string) => "'" + arg.replace(/'/g, "'\\''") + "'";
    const wrappedCommand = [
      'bash',
      '-lc',
      `export SHELL=/bin/bash; ${command.map(shellEscape).join(' ')}`,
    ];

    kubeExec
      .exec(
        ns,
        podName,
        containerName,
        wrappedCommand,
        stdoutStream,
        stderrStream,
        null,
        false,
        (status) => {
          clearTimeout(timer);
          const exitCode =
            status.status === 'Success'
              ? 0
              : parseInt(
                  status.details?.causes?.find(
                    (c: any) => c.reason === 'ExitCode',
                  )?.message ?? '1',
                  10,
                );
          resolve({ stdout, stderr, exitCode });
        },
      )
      .catch((err) => {
        clearTimeout(timer);
        reject(err);
      });
  });
}
